<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', '/password/process-reset-password');
	echo $this->form()->openTag($form);
        
        echo $this->formHidden($form->get('code'));
?>
	<div class="forget-password-form-content">
		<?= $this->formLabel($form->get('newpass')); ?>
		<div class="form-input"><?= $this->formElement($form->get('newpass')); ?></div>
		<div class="form-error"><?= $this->formElementErrors($form->get('newpass')); ?></div>
                
		<?= $this->formLabel($form->get('confirm')); ?>
                <div class="form-input"><?= $this->formElement($form->get('confirm')); ?></div>
		<div class="form-error"><?= $this->formElementErrors($form->get('confirm')); ?></div>

		<div class="form-error"><?= $this->bad_confirm; ?></div>

		<div class="form-input form-input-submit"><?= $this->formElement($form->get('submit')); ?></div>
		<div class="form-error"><?= $this->formElementErrors($form->get('submit')); ?></div>	

	</div>

<?php echo $this->form()->closeTag() ?>