<div class="static-page-title">Баннер-кнопка</div>


<div class="banner-button">
    <div class="banner-button-wrap">
        <div class="banner-button-image">
            <a href="http://ardfo.by/" target="_blank" title="ARDFO.BY - Объявления и Реклама">
                <img src="http://ardfo.by/img/ardfo-banner.png" width="88" height="31" border="0" alt="ARDFO.BY - Объявления и Реклама"></a>
        </div>
        <div class="banner-button-link">
            <textarea rows="3"  readonly></textarea>
        </div>
    </div>
</div>