<div class="register-options">
	<div class="register-options-row first">
		<p>Приветствуем вас на информационном ресурсе <a href="/">www.ardfo.by</a></p>
	</div>

	<div class="register-options-row second">
		<p>Пожалуйста, выберите форму регистрации</p>
	</div>

	<div class="register-options-row third">
		<div class="register-options-btn">
			<a class="" href="<?=$this->url('register', array('action' => 'legal-register')); ?>">Юридическое лицо</a>
		</div>
		<div class="register-options-btn">
			<a class="" href="<?=$this->url('register', array('action' => 'individual-register')); ?>">Индивидуальный прдприниматель</a>
		</div>
		<div class="register-options-btn">
			<a class="" href="<?=$this->url('register', array('action' => 'physical-register')); ?>">Физическое лицо</a>
		</div>
	</div>	
    
        <div class="register-options-row fourth">
            <div class="register-price-list"><a href="#"h>Прейскурант цен</a></div>
	</div>
        
        <div class="price-image">
            
        </div>
        
        
        <div class="banner-button">
            <p>*Баннер-кнопка</p>
            <div class="banner-button-wrap">
                <div class="banner-button-image">
                    <a href="http://ardfo.by/" target="_blank" title="ARDFO.BY - Объявления и Реклама">
                    <img src="http://ardfo.by/img/ardfo-banner.png" width="88" height="31" border="0" alt="ARDFO.BY - Объявления и Реклама"></a>
                </div>
                <div class="banner-button-link">
                    <textarea rows="3"  readonly></textarea>
                </div>
            </div>
        </div>
</div>