<?php
$messages = $this->flashMessenger()->getMessagesFromNamespace($form->getName());
if (count($messages)) {
    foreach ($messages as $message) {
        $form->setMessages($message);
    }
}
?>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('category',array('action' => 'process')));
?>

<?php echo $this->form()->openTag($form); ?>
<div class="form-list">
    <?php foreach ($form as $element) : ?>
        <div class="<?php echo 'block-' . $element->getName(); ?>">
            <div class="label"><?php echo $this->formLabel($element); ?></div>
            <div class="error"><?php echo $this->formElementErrors($element); ?></div>
            <div class="field"><?php echo $this->formElement($element); ?></div>
        </div>
    <?php endforeach; ?>
</div>
<?php echo $this->form()->closeTag(); ?>