<?php
	$form = $this->form;
	$form->prepare();
	$form->setAttribute('action', '/auth/authenticate');
	echo $this->form()->openTag($form);
?>
	<div class="login-form-content">
		<?php if (!empty($this->messages)): ?>
			<div class="form-error"><?= $this->messages[0]; ?></div>
		<?php endif; ?>

		<?= $this->formLabel($form->get('email')); ?>
		<div class="form-input"><?= $this->formElement($form->get('email')); ?></div>
		<div class="form-error"><?= $this->formElementErrors($form->get('email')); ?></div>

		<?= $this->formLabel($form->get('password')); ?>
		<div class="form-input"><?= $this->formElement($form->get('password')); ?></div>
		<div class="form-error"><?= $this->formElementErrors($form->get('password')); ?></div>

		<div class="form-input form-input-submit"><?= $this->formElement($form->get('submit')); ?></div>
		<div class="form-error"><?= $this->formElementErrors($form->get('submit')); ?></div>	
	</div>
	
<?php echo $this->form()->closeTag() ?>

<div class="login-forget-password">
	<a href="<?= $this->url('password', array('action' => 'forget')); ?>">Забыли пароль?</a>
</div>
